from __future__ import annotations

import datetime as dt
import html
import json
import math
import re
import shutil
import time
from collections.abc import Iterable, Sequence
from pathlib import Path
from urllib.parse import quote
from xml.dom import minidom
from xml.etree import ElementTree as ET

import numpy as np

from .assets import resolve_face_sionna_material, sionna_material_itu_type
from .geometry import build_room_mesh, load_obj_material_mesh, load_obj_mesh, transform_vertices
from .models import (
    Asset,
    BistroBaseScene,
    Front3DBaseScene,
    ObjMesh,
    PlacedAsset,
    Rect2D,
    Room,
    SceneMeshArrays,
    SionnaAssetPart,
    SionnaXmlShape,
)
from .paths import SIONNA_BASE_SCENE_MATERIAL, portable_path


def sanitize_path_segment(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("._")
    return safe or "item"


def sanitize_xml_id(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("._-")
    if not safe:
        return "shape"
    if not re.match(r"[A-Za-z_]", safe):
        safe = f"shape_{safe}"
    return safe


def format_xml_float(value: float) -> str:
    if abs(value) < 1e-10:
        value = 0.0
    return f"{value:.9g}"


def relative_posix(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def obj_vertex_lines(vertices: Iterable[Sequence[float]]) -> list[str]:
    return [f"v {x:.6f} {y:.6f} {z:.6f}\n" for x, y, z in vertices]


def obj_face_lines(faces: list[list[int]], vertex_offset: int = 0) -> list[str]:
    return ["f " + " ".join(str(vertex_offset + index + 1) for index in face) + "\n" for face in faces]


def triangulated_face_indices(faces: list[list[int]], vertex_offset: int = 0) -> list[tuple[int, int, int]]:
    triangles: list[tuple[int, int, int]] = []
    for face in faces:
        if len(face) < 3:
            continue
        first = int(face[0]) + vertex_offset
        for index in range(1, len(face) - 1):
            triangles.append((first, int(face[index]) + vertex_offset, int(face[index + 1]) + vertex_offset))
    return triangles


def write_clean_obj_subset(
    path: Path,
    object_name: str,
    vertices: list[tuple[float, float, float]],
    faces: list[list[int]],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    index_map: dict[int, int] = {}
    subset_vertices: list[tuple[float, float, float]] = []
    for face in faces:
        for index in face:
            if index < 0 or index >= len(vertices):
                raise ValueError(f"OBJ face index out of range while writing {path}: {index}")
            if index not in index_map:
                index_map[index] = len(subset_vertices) + 1
                subset_vertices.append(vertices[index])

    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.writelines(
            [
                "# Generated by SceneGen for Sionna RT\n",
                f"o {sanitize_xml_id(object_name)}\n",
                *obj_vertex_lines(subset_vertices),
                *("f " + " ".join(str(index_map[index]) for index in face) + "\n" for face in faces),
            ]
        )


def write_clean_obj_full(
    path: Path,
    object_name: str,
    vertices: list[tuple[float, float, float]],
    faces: list[list[int]],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("# Generated by SceneGen for Sionna RT\n")
        handle.write(f"o {sanitize_xml_id(object_name)}\n")
        handle.writelines(obj_vertex_lines(vertices))
        handle.writelines(obj_face_lines(faces))


def write_clean_obj_full_from_source(path: Path, object_name: str, source_obj: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with source_obj.open("r", encoding="utf-8", errors="ignore") as source, path.open(
        "w",
        encoding="utf-8",
        newline="\n",
    ) as handle:
        handle.write("# Generated by SceneGen for Sionna RT\n")
        handle.write(f"o {sanitize_xml_id(object_name)}\n")
        for line in source:
            if line.startswith(("v ", "vt ", "vn ", "f ")):
                handle.write(line if line.endswith("\n") else f"{line}\n")


def write_clean_obj_mesh(path: Path, object_name: str, mesh: ObjMesh) -> None:
    write_clean_obj_subset(path, object_name, mesh.vertices, mesh.faces)


def transform_matrix_for_placement(placed: PlacedAsset) -> tuple[float, ...]:
    if placed.transform_matrix_4x4_row_major is not None:
        return placed.transform_matrix_4x4_row_major

    cos_yaw = math.cos(placed.yaw)
    sin_yaw = math.sin(placed.yaw)
    return (
        cos_yaw,
        -sin_yaw,
        0.0,
        placed.x,
        sin_yaw,
        cos_yaw,
        0.0,
        placed.y,
        0.0,
        0.0,
        1.0,
        placed.z,
        0.0,
        0.0,
        0.0,
        1.0,
    )


def transform_vertices_array(mesh: ObjMesh, placed: PlacedAsset) -> np.ndarray:
    vertices = np.asarray(mesh.vertices, dtype=np.float64)
    if vertices.size == 0:
        return vertices.reshape((0, 3))
    if placed.transform_matrix_4x4_row_major is not None:
        matrix = np.asarray(placed.transform_matrix_4x4_row_major, dtype=np.float64).reshape((4, 4))
        return vertices @ matrix[:3, :3].T + matrix[:3, 3]

    cos_yaw = math.cos(placed.yaw)
    sin_yaw = math.sin(placed.yaw)
    transformed = np.empty_like(vertices)
    transformed[:, 0] = placed.x + cos_yaw * vertices[:, 0] - sin_yaw * vertices[:, 1]
    transformed[:, 1] = placed.y + sin_yaw * vertices[:, 0] + cos_yaw * vertices[:, 1]
    transformed[:, 2] = placed.z + vertices[:, 2]
    return transformed


def export_sionna_asset_parts(
    scene_dir: Path,
    assets_dir: Path,
    asset: Asset,
    cache: dict[Path, list[SionnaAssetPart]],
) -> list[SionnaAssetPart]:
    cached = cache.get(asset.obj_file)
    if cached is not None:
        return cached

    material_mesh = load_obj_material_mesh(asset.obj_file)
    faces_by_sionna: dict[str, list[list[int]]] = {}
    total_face_count = 0
    for source_material, faces in material_mesh.faces_by_material.items():
        total_face_count += len(faces)
        material_name = resolve_face_sionna_material(asset, source_material)
        faces_by_sionna.setdefault(material_name, []).extend(faces)

    asset_dir_name = sanitize_path_segment(asset.export_name)
    asset_dir = assets_dir / asset_dir_name
    asset_stem = sanitize_path_segment(asset.export_name)
    parts: list[SionnaAssetPart] = []
    for material_name in sorted(faces_by_sionna):
        faces = faces_by_sionna[material_name]
        material_suffix = sanitize_path_segment(sionna_material_itu_type(material_name))
        path = asset_dir / f"{asset_stem}__{material_suffix}.obj"
        if len(faces_by_sionna) == 1 and len(faces) == total_face_count:
            write_clean_obj_full_from_source(path, f"{asset.export_name}_{material_suffix}", asset.obj_file)
        else:
            write_clean_obj_subset(
                path,
                f"{asset.export_name}_{material_suffix}",
                material_mesh.vertices,
                faces,
            )
        parts.append(
            SionnaAssetPart(
                filename=relative_posix(path, scene_dir),
                material_name=material_name,
                face_count=len(faces),
            )
        )

    cache[asset.obj_file] = parts
    return parts


def export_front3d_base_parts(
    scene_dir: Path,
    assets_dir: Path,
    base_scene: Front3DBaseScene,
) -> list[SionnaAssetPart]:
    material_mesh = load_obj_material_mesh(base_scene.scene_obj)
    material_lookup: dict[str, str] = {}
    for source, material_name in base_scene.source_to_sionna_material.items():
        material_lookup[source] = material_name
        material_lookup[sanitize_path_segment(source)] = material_name

    base_dir = assets_dir / "empty_scene"
    offset_x, offset_y, offset_z = base_scene.world_offset
    vertices = [(x + offset_x, y + offset_y, z + offset_z) for x, y, z in material_mesh.vertices]
    parts: list[SionnaAssetPart] = []
    for source_material, faces in sorted(material_mesh.faces_by_material.items(), key=lambda item: str(item[0])):
        material_name = material_lookup.get(source_material or "", SIONNA_BASE_SCENE_MATERIAL)
        material_suffix = sanitize_path_segment(sionna_material_itu_type(material_name))
        source_suffix = sanitize_path_segment(source_material or "default")
        path = base_dir / f"front3d_architecture__{source_suffix}__{material_suffix}.obj"
        write_clean_obj_subset(
            path,
            f"front3d_architecture_{source_suffix}_{material_suffix}",
            vertices,
            faces,
        )
        parts.append(
            SionnaAssetPart(
                filename=relative_posix(path, scene_dir),
                material_name=material_name,
                face_count=len(faces),
            )
        )
    return parts


def build_sionna_scene_xml(shapes: list[SionnaXmlShape]) -> str:
    scene = ET.Element("scene", version="3.0.0")
    for material_name in sorted({shape.material_name for shape in shapes}):
        bsdf = ET.SubElement(scene, "bsdf", type="itu-radio-material", id=material_name)
        ET.SubElement(bsdf, "string", name="type", value=sionna_material_itu_type(material_name))

    for shape_info in shapes:
        shape = ET.SubElement(scene, "shape", type="obj", id=sanitize_xml_id(shape_info.shape_id))
        ET.SubElement(shape, "string", name="filename", value=shape_info.filename)
        if shape_info.transform is not None:
            transform = ET.SubElement(shape, "transform", name="to_world")
            ET.SubElement(
                transform,
                "matrix",
                value=" ".join(format_xml_float(value) for value in shape_info.transform),
            )
        ET.SubElement(shape, "ref", id=shape_info.material_name)

    rough = ET.tostring(scene, encoding="utf-8")
    return minidom.parseString(rough).toprettyxml(indent="  ", encoding="utf-8").decode("utf-8")


def write_sionna_scene_assets(
    output_dir: Path,
    base_mesh: ObjMesh,
    placements: list[PlacedAsset],
) -> dict[str, object]:
    assets_dir = output_dir / "assets"
    empty_scene_obj = assets_dir / "empty_scene" / "scene.obj"
    write_clean_obj_mesh(empty_scene_obj, "empty_scene", base_mesh)

    shapes = [
        SionnaXmlShape(
            shape_id="empty_scene",
            filename=relative_posix(empty_scene_obj, output_dir),
            material_name=SIONNA_BASE_SCENE_MATERIAL,
        )
    ]
    asset_cache: dict[Path, list[SionnaAssetPart]] = {}
    placement_asset_parts: list[dict[str, object]] = []
    for placed in placements:
        parts = export_sionna_asset_parts(output_dir, assets_dir, placed.asset, asset_cache)
        transform = transform_matrix_for_placement(placed)
        placement_parts: list[dict[str, object]] = []
        for part in parts:
            material_suffix = sanitize_path_segment(sionna_material_itu_type(part.material_name))
            shape_id = f"{placed.instance_name}_{material_suffix}"
            shapes.append(
                SionnaXmlShape(
                    shape_id=shape_id,
                    filename=part.filename,
                    material_name=part.material_name,
                    transform=transform,
                )
            )
            placement_parts.append(
                {
                    "shape_id": sanitize_xml_id(shape_id),
                    "asset_obj": part.filename,
                    "sionna_material_name": part.material_name,
                    "itu_type": sionna_material_itu_type(part.material_name),
                    "face_count": part.face_count,
                }
            )
        placement_asset_parts.append(
            {
                "instance_name": placed.instance_name,
                "asset_name": placed.asset.name,
                "parts": placement_parts,
            }
        )

    (output_dir / "scene.xml").write_text(build_sionna_scene_xml(shapes), encoding="utf-8")
    return {
        "assets_dir": portable_path(assets_dir, output_dir),
        "empty_scene_obj": relative_posix(empty_scene_obj, output_dir),
        "scene_xml": portable_path(output_dir / "scene.xml", output_dir),
        "shape_count": len(shapes),
        "asset_file_count": sum(len(parts) for parts in asset_cache.values()) + 1,
        "materials": sorted({shape.material_name for shape in shapes}),
        "placements": placement_asset_parts,
    }


def write_front3d_sionna_scene_assets(
    output_dir: Path,
    base_scene: Front3DBaseScene,
    placements: list[PlacedAsset],
) -> dict[str, object]:
    timings_s: dict[str, float] = {}
    assets_dir = output_dir / "assets"
    started = time.perf_counter()
    base_parts = export_front3d_base_parts(output_dir, assets_dir, base_scene)
    timings_s["export_base_parts"] = round(time.perf_counter() - started, 6)
    shapes = [
        SionnaXmlShape(
            shape_id=f"empty_scene_{index:04d}_{sionna_material_itu_type(part.material_name)}",
            filename=part.filename,
            material_name=part.material_name,
        )
        for index, part in enumerate(base_parts)
    ]
    asset_cache: dict[Path, list[SionnaAssetPart]] = {}
    placement_asset_parts: list[dict[str, object]] = []
    started = time.perf_counter()
    for placed in placements:
        parts = export_sionna_asset_parts(output_dir, assets_dir, placed.asset, asset_cache)
        transform = transform_matrix_for_placement(placed)
        placement_parts: list[dict[str, object]] = []
        for part in parts:
            material_suffix = sanitize_path_segment(sionna_material_itu_type(part.material_name))
            shape_id = f"{placed.instance_name}_{material_suffix}"
            shapes.append(
                SionnaXmlShape(
                    shape_id=shape_id,
                    filename=part.filename,
                    material_name=part.material_name,
                    transform=transform,
                )
            )
            placement_parts.append(
                {
                    "shape_id": sanitize_xml_id(shape_id),
                    "asset_obj": part.filename,
                    "sionna_material_name": part.material_name,
                    "itu_type": sionna_material_itu_type(part.material_name),
                    "face_count": part.face_count,
                }
            )
        placement_asset_parts.append(
            {
                "instance_name": placed.instance_name,
                "asset_name": placed.asset.name,
                "parts": placement_parts,
            }
        )
    timings_s["export_object_parts"] = round(time.perf_counter() - started, 6)

    started = time.perf_counter()
    (output_dir / "scene.xml").write_text(build_sionna_scene_xml(shapes), encoding="utf-8")
    timings_s["write_xml"] = round(time.perf_counter() - started, 6)
    return {
        "assets_dir": portable_path(assets_dir, output_dir),
        "empty_scene_obj": portable_path(base_scene.scene_obj, output_dir),
        "scene_xml": portable_path(output_dir / "scene.xml", output_dir),
        "shape_count": len(shapes),
        "asset_file_count": sum(len(parts) for parts in asset_cache.values()) + len(base_parts),
        "materials": sorted({shape.material_name for shape in shapes}),
        "base_scene_parts": [
            {
                "asset_obj": part.filename,
                "sionna_material_name": part.material_name,
                "itu_type": sionna_material_itu_type(part.material_name),
                "face_count": part.face_count,
            }
            for part in base_parts
        ],
        "placements": placement_asset_parts,
        "timings_s": timings_s,
    }


def write_obj(path: Path, room: Room, placements: list[PlacedAsset]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    room_mesh = build_room_mesh(room)
    mesh_cache: dict[Path, ObjMesh] = {}
    vertex_offset = 0
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.writelines(["# Generated by SceneGen\n", "o generated_room\n"])
        handle.writelines(obj_vertex_lines(room_mesh.vertices))
        handle.writelines(obj_face_lines(room_mesh.faces, vertex_offset))
        vertex_offset += len(room_mesh.vertices)

        for placed in placements:
            mesh = mesh_cache.setdefault(placed.asset.obj_file, load_obj_mesh(placed.asset.obj_file))
            handle.write(f"o {placed.instance_name}\n")
            handle.writelines(obj_vertex_lines(transform_vertices(mesh, placed)))
            handle.writelines(obj_face_lines(mesh.faces, vertex_offset))
            vertex_offset += len(mesh.vertices)


def write_bistro_obj(path: Path, base_scene: BistroBaseScene, placements: list[PlacedAsset]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    base_mesh = load_obj_mesh(base_scene.scene_obj)
    mesh_cache: dict[Path, ObjMesh] = {}
    vertex_offset = 0
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.writelines(["# Generated by SceneGen --mode bistro\n", "o empty_scene\n"])
        handle.writelines(obj_vertex_lines(base_mesh.vertices))
        handle.writelines(obj_face_lines(base_mesh.faces, vertex_offset))
        vertex_offset += len(base_mesh.vertices)

        for placed in placements:
            mesh = mesh_cache.setdefault(placed.asset.obj_file, load_obj_mesh(placed.asset.obj_file))
            handle.write(f"o {placed.instance_name}\n")
            handle.writelines(obj_vertex_lines(transform_vertices(mesh, placed)))
            handle.writelines(obj_face_lines(mesh.faces, vertex_offset))
            vertex_offset += len(mesh.vertices)


def write_front3d_obj(
    path: Path,
    base_scene: Front3DBaseScene,
    placements: list[PlacedAsset],
    *,
    collect_mesh_arrays: bool = False,
    mode: str = "front3d",
) -> SceneMeshArrays | None:
    path.parent.mkdir(parents=True, exist_ok=True)
    base_mesh = load_obj_mesh(base_scene.scene_obj)
    mesh_cache: dict[Path, ObjMesh] = {}
    vertex_chunks: list[np.ndarray] = []
    triangle_chunks: list[list[tuple[int, int, int]]] = []
    vertex_offset = 0
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.writelines(
            [
                f"# Generated by SceneGen --mode {mode}\n",
                f"o front3d_architecture_{sanitize_xml_id(base_scene.scene_id)}\n",
            ]
        )
        offset_x, offset_y, offset_z = base_scene.world_offset
        base_vertices = np.asarray(base_mesh.vertices, dtype=np.float64)
        if base_vertices.size:
            base_vertices = base_vertices.copy()
            base_vertices[:, 0] += offset_x
            base_vertices[:, 1] += offset_y
            base_vertices[:, 2] += offset_z
        handle.writelines(obj_vertex_lines(base_vertices.tolist()))
        handle.writelines(obj_face_lines(base_mesh.faces, vertex_offset))
        if collect_mesh_arrays:
            vertex_chunks.append(base_vertices)
            triangle_chunks.append(triangulated_face_indices(base_mesh.faces, vertex_offset))
        vertex_offset += len(base_mesh.vertices)

        for placed in placements:
            mesh = mesh_cache.setdefault(placed.asset.obj_file, load_obj_mesh(placed.asset.obj_file))
            handle.write(f"o {placed.instance_name}\n")
            transformed_vertices = transform_vertices_array(mesh, placed)
            handle.writelines(obj_vertex_lines(transformed_vertices.tolist()))
            handle.writelines(obj_face_lines(mesh.faces, vertex_offset))
            if collect_mesh_arrays:
                vertex_chunks.append(transformed_vertices)
                triangle_chunks.append(triangulated_face_indices(mesh.faces, vertex_offset))
            vertex_offset += len(mesh.vertices)
    if not collect_mesh_arrays:
        return None
    vertices = (
        np.concatenate([np.asarray(chunk, dtype=np.float32) for chunk in vertex_chunks], axis=0)
        if vertex_chunks
        else np.zeros((0, 3), dtype=np.float32)
    )
    faces = (
        np.concatenate([np.asarray(chunk, dtype=np.int32) for chunk in triangle_chunks], axis=0)
        if triangle_chunks
        else np.zeros((0, 3), dtype=np.int32)
    )
    return SceneMeshArrays(vertices=vertices, faces=faces, source="write_front3d_obj")


def collect_front3d_scene_mesh_arrays(
    base_scene: Front3DBaseScene,
    placements: list[PlacedAsset],
    *,
    source: str = "collect_front3d_scene_mesh_arrays",
) -> SceneMeshArrays:
    base_mesh = load_obj_mesh(base_scene.scene_obj)
    mesh_cache: dict[Path, ObjMesh] = {}
    vertex_chunks: list[np.ndarray] = []
    triangle_chunks: list[list[tuple[int, int, int]]] = []
    vertex_offset = 0

    offset_x, offset_y, offset_z = base_scene.world_offset
    base_vertices = np.asarray(base_mesh.vertices, dtype=np.float64)
    if base_vertices.size:
        base_vertices = base_vertices.copy()
        base_vertices[:, 0] += offset_x
        base_vertices[:, 1] += offset_y
        base_vertices[:, 2] += offset_z
    vertex_chunks.append(base_vertices)
    triangle_chunks.append(triangulated_face_indices(base_mesh.faces, vertex_offset))
    vertex_offset += len(base_mesh.vertices)

    for placed in placements:
        mesh = mesh_cache.setdefault(placed.asset.obj_file, load_obj_mesh(placed.asset.obj_file))
        transformed_vertices = transform_vertices_array(mesh, placed)
        vertex_chunks.append(transformed_vertices)
        triangle_chunks.append(triangulated_face_indices(mesh.faces, vertex_offset))
        vertex_offset += len(mesh.vertices)

    vertices = (
        np.concatenate([np.asarray(chunk, dtype=np.float32) for chunk in vertex_chunks], axis=0)
        if vertex_chunks
        else np.zeros((0, 3), dtype=np.float32)
    )
    faces = (
        np.concatenate([np.asarray(chunk, dtype=np.int32) for chunk in triangle_chunks], axis=0)
        if triangle_chunks
        else np.zeros((0, 3), dtype=np.int32)
    )
    return SceneMeshArrays(vertices=vertices, faces=faces, source=source)


def placement_to_json(placed: PlacedAsset, path_root: Path) -> dict[str, object]:
    payload: dict[str, object] = {
        "instance_name": placed.instance_name,
        "asset_name": placed.asset.name,
        "asset_obj": portable_path(placed.asset.obj_file, path_root),
        "placement_class": placed.asset.placement_class,
        "sionna_materials": list(placed.asset.sionna_material_names),
        "source_to_sionna_material": placed.asset.source_to_sionna_material,
        "support_type": placed.support_type,
        "parent": placed.parent,
        "translation": [round(placed.x, 6), round(placed.y, 6), round(placed.z, 6)],
        "yaw_radians": round(placed.yaw, 6),
        "bbox": {
            "min": [round(placed.min_x, 6), round(placed.min_y, 6), round(placed.min_z, 6)],
            "max": [round(placed.max_x, 6), round(placed.max_y, 6), round(placed.max_z, 6)],
        },
        "asset_dimensions": {
            "width_x": placed.asset.width,
            "length_y": placed.asset.length,
            "height_z": placed.asset.height,
        },
    }
    if placed.transform_matrix_4x4_row_major is not None:
        payload["transform_matrix_4x4_row_major"] = [
            round(value, 9) for value in placed.transform_matrix_4x4_row_major
        ]
    if placed.source_ids:
        payload["source_ids"] = placed.source_ids
    if placed.metadata:
        payload["metadata"] = placed.metadata
    return payload


def write_scene_files(
    output_dir: Path,
    room: Room,
    placements: list[PlacedAsset],
    scene_index: int,
    seed: int,
    rng: object,
) -> dict[str, object]:
    output_dir.mkdir(parents=True, exist_ok=True)
    write_obj(output_dir / "scene.obj", room, placements)
    sionna_assets = write_sionna_scene_assets(output_dir, build_room_mesh(room), placements)
    placement_payload = {
        "scene_index": scene_index,
        "seed": seed,
        "mode": "generated",
        "room": {"width": room.width, "length": room.length, "height": room.height},
        "forbidden_xy_rects": [],
        "forbidden_z_ignored": False,
        "sionna_assets": sionna_assets,
        "placement_count": len(placements),
        "placements": [placement_to_json(placement, output_dir) for placement in placements],
    }
    (output_dir / "placements.json").write_text(json.dumps(placement_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return scene_record(output_dir, scene_index, seed, sionna_assets, placements)


def write_bistro_scene_files(
    output_dir: Path,
    base_scene: BistroBaseScene,
    placements: list[PlacedAsset],
    scene_index: int,
    seed: int,
    rng: object,
    forbidden_xy_rects: tuple[Rect2D, ...],
) -> dict[str, object]:
    output_dir.mkdir(parents=True, exist_ok=True)
    write_bistro_obj(output_dir / "scene.obj", base_scene, placements)
    sionna_assets = write_sionna_scene_assets(output_dir, load_obj_mesh(base_scene.scene_obj), placements)
    placement_payload = {
        "scene_index": scene_index,
        "seed": seed,
        "mode": "bistro",
        "forbidden_xy_rects": [list(rect) for rect in forbidden_xy_rects],
        "forbidden_z_ignored": True,
        "sionna_assets": sionna_assets,
        "base_scene": base_scene_summary(base_scene, output_dir),
        "placement_count": len(placements),
        "placements": [placement_to_json(placement, output_dir) for placement in placements],
    }
    (output_dir / "placements.json").write_text(json.dumps(placement_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return scene_record(output_dir, scene_index, seed, sionna_assets, placements)


def write_front3d_scene_files(
    output_dir: Path,
    base_scene: Front3DBaseScene,
    placements: list[PlacedAsset],
    skipped_objects: list[dict[str, object]],
    scene_index: int,
    seed: int,
    rng: object,
    collect_floorplan_mesh_arrays: bool = True,
    mode: str = "front3d",
    write_scene_obj: bool = True,
    write_sionna_assets: bool = True,
) -> tuple[dict[str, object], SceneMeshArrays | None]:
    timings_s: dict[str, float] = {}
    output_dir.mkdir(parents=True, exist_ok=True)
    started = time.perf_counter()
    if write_scene_obj:
        floorplan_mesh_arrays = write_front3d_obj(
            output_dir / "scene.obj",
            base_scene,
            placements,
            collect_mesh_arrays=collect_floorplan_mesh_arrays,
            mode=mode,
        )
    elif collect_floorplan_mesh_arrays:
        floorplan_mesh_arrays = collect_front3d_scene_mesh_arrays(base_scene, placements)
    else:
        floorplan_mesh_arrays = None
    timings_s["write_scene_obj"] = round(time.perf_counter() - started, 6)
    started = time.perf_counter()
    if write_sionna_assets:
        sionna_assets = write_front3d_sionna_scene_assets(output_dir, base_scene, placements)
    else:
        sionna_assets = {
            "shape_count": 0,
            "materials": [],
            "asset_parts": [],
            "skipped": True,
            "reason": "output.write_sionna_assets=false",
        }
    timings_s["write_sionna_assets"] = round(time.perf_counter() - started, 6)
    started = time.perf_counter()
    placement_payload = {
        "scene_index": scene_index,
        "seed": seed,
        "mode": mode,
        "front3d_scene_id": base_scene.scene_id,
        "source_scene": portable_path(base_scene.source_scene_json, output_dir),
        "architecture": base_scene_summary(base_scene, output_dir),
        "skipped_objects": skipped_objects,
        "skipped_object_count": len(skipped_objects),
        "sionna_assets": sionna_assets,
        "placement_count": len(placements),
        "placements": [placement_to_json(placement, output_dir) for placement in placements],
    }
    (output_dir / "placements.json").write_text(json.dumps(placement_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    timings_s["write_placements_json"] = round(time.perf_counter() - started, 6)
    record = scene_record(output_dir, scene_index, seed, sionna_assets, placements)
    record["front3d_scene_id"] = base_scene.scene_id
    if mode != "front3d":
        record["mode"] = mode
    record["source_scene"] = portable_path(base_scene.source_scene_json, output_dir.parent)
    record["skipped_object_count"] = len(skipped_objects)
    record["skipped_objects"] = skipped_objects
    if not write_scene_obj:
        record["scene_obj"] = None
    if not write_sionna_assets:
        record["scene_xml"] = None
        record["assets_dir"] = None
        record["sionna_assets_skipped"] = True
    record["build_timings_s"] = timings_s
    return record, floorplan_mesh_arrays


def scene_record(
    output_dir: Path,
    scene_index: int,
    seed: int,
    sionna_assets: dict[str, object],
    placements: list[PlacedAsset],
) -> dict[str, object]:
    run_dir = output_dir.parent
    return {
        "scene_index": scene_index,
        "seed": seed,
        "scene_dir": portable_path(output_dir, run_dir),
        "scene_obj": portable_path(output_dir / "scene.obj", run_dir),
        "scene_xml": portable_path(output_dir / "scene.xml", run_dir),
        "assets_dir": portable_path(output_dir / "assets", run_dir),
        "sionna_shape_count": sionna_assets["shape_count"],
        "sionna_materials": sionna_assets["materials"],
        "placement_count": len(placements),
    }


def base_scene_summary(base_scene: BistroBaseScene | Front3DBaseScene, path_root: Path | None = None) -> dict[str, object]:
    if isinstance(base_scene, Front3DBaseScene):
        root = path_root or base_scene.scene_obj.parent
        return {
            "scene_id": base_scene.scene_id,
            "scene_obj": portable_path(base_scene.scene_obj, root),
            "source_scene_json": portable_path(base_scene.source_scene_json, root),
            "metadata_json": portable_path(base_scene.metadata_json, root),
            "bbox_min": [round(value, 6) for value in base_scene.bbox_min],
            "bbox_max": [round(value, 6) for value in base_scene.bbox_max],
            "source_bbox_min": [round(value, 6) for value in base_scene.source_bbox_min],
            "source_bbox_max": [round(value, 6) for value in base_scene.source_bbox_max],
            "world_offset": [round(value, 6) for value in base_scene.world_offset],
            "materials": list(base_scene.sionna_material_names),
        }

    root = path_root or base_scene.base_dir
    return {
        "base_dir": portable_path(base_scene.base_dir, root),
        "scene_obj": portable_path(base_scene.scene_obj, root),
        "bbox_min": [round(value, 6) for value in base_scene.bbox_min],
        "bbox_max": [round(value, 6) for value in base_scene.bbox_max],
        "floor_z": round(base_scene.floor_z, 6),
        "floor_triangle_count": len(base_scene.floor_triangles),
        "floor_area": round(sum(tri.area for tri in base_scene.floor_triangles), 6),
        "support_surface_count": len(base_scene.support_surfaces),
        "static_obstacle_count": len(base_scene.static_obstacles),
    }


def make_timestamp() -> str:
    return dt.datetime.now().strftime("%Y%m%d%H%M%S")


def height_token(value: float) -> str:
    return f"{value:g}".replace("-", "m").replace(".", "p")


def collect_scene_objs(run_dir: Path, scene_records: list[dict[str, object]], scene_prefix: str) -> dict[str, object]:
    summary_dir = run_dir / "summary" / "obj"
    summary_dir.mkdir(parents=True, exist_ok=True)
    copied: list[dict[str, str]] = []
    for record in scene_records:
        scene_index = int(record["scene_index"])
        scene_obj = record.get("scene_obj")
        if not isinstance(scene_obj, str) or not scene_obj:
            continue
        source = Path(scene_obj)
        if not source.is_absolute():
            source = run_dir / source
        if not source.is_file():
            continue
        destination = summary_dir / f"{scene_prefix}_{scene_index:04d}.obj"
        shutil.copy2(source, destination)
        copied.append(
            {
                "source": portable_path(source, run_dir),
                "destination": portable_path(destination, run_dir),
            }
        )

    copy_manifest = {
        "summary_dir": portable_path(summary_dir, run_dir),
        "count": len(copied),
        "objects": copied,
    }
    (summary_dir / "copy_manifest.json").write_text(
        json.dumps(copy_manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return copy_manifest


def collect_raw_floorplans(run_dir: Path, scene_records: list[dict[str, object]], scene_prefix: str) -> dict[str, object]:
    summary_dir = run_dir / "summary" / "floorplan"
    summary_dir.mkdir(parents=True, exist_ok=True)
    copied: list[dict[str, str]] = []

    for record in scene_records:
        scene_index = int(record["scene_index"])
        floorplan = record.get("floorplan")
        if not isinstance(floorplan, dict) or not floorplan.get("ok", False):
            continue
        geometry = floorplan.get("geometry")
        if not isinstance(geometry, dict):
            continue
        raw_path = geometry.get("raw")
        if not isinstance(raw_path, str) or not raw_path:
            continue

        scene_dir = Path(str(record["scene_dir"]))
        if not scene_dir.is_absolute():
            scene_dir = run_dir / scene_dir
        source = Path(raw_path)
        if not source.is_absolute():
            source = scene_dir / source
        if not source.is_file():
            continue

        destination = summary_dir / f"{scene_prefix}_{scene_index:04d}_{source.name}"
        shutil.copy2(source, destination)
        copied.append(
            {
                "scene_index": str(scene_index),
                "source": portable_path(source, run_dir),
                "destination": portable_path(destination, run_dir),
            }
        )

    copy_manifest = {
        "summary_dir": portable_path(summary_dir, run_dir),
        "count": len(copied),
        "images": copied,
    }
    (summary_dir / "copy_manifest.json").write_text(
        json.dumps(copy_manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return copy_manifest


def collect_label_floorplans(run_dir: Path, scene_records: list[dict[str, object]], scene_prefix: str) -> dict[str, object]:
    summary_dir = run_dir / "summary" / "label_floorplan"
    summary_dir.mkdir(parents=True, exist_ok=True)
    copied: list[dict[str, str]] = []
    groups: dict[str, dict[str, object]] = {}

    for record in scene_records:
        scene_index = int(record["scene_index"])
        label = record.get("label")
        if not isinstance(label, dict) or not label.get("ok", False):
            continue
        variants = label.get("variants")
        if not isinstance(variants, list):
            continue
        for variant in variants:
            if not isinstance(variant, dict):
                continue
            overlay = variant.get("overlay")
            if not isinstance(overlay, dict):
                continue
            overlay_path = overlay.get("image")
            if not isinstance(overlay_path, str) or not overlay_path:
                continue
            grid_resolution = variant.get("grid_resolution_m")
            if not isinstance(grid_resolution, int | float):
                continue
            source = Path(overlay_path)
            if not source.is_absolute():
                source = run_dir / source
            if not source.is_file():
                continue

            grid_name = height_token(float(grid_resolution))
            grid_dir = summary_dir / grid_name
            grid_dir.mkdir(parents=True, exist_ok=True)
            variant_name = str(variant.get("name") or source.stem)
            destination = grid_dir / f"{scene_prefix}_{scene_index:04d}_{variant_name}.png"
            shutil.copy2(source, destination)
            item = {
                "scene_index": str(scene_index),
                "variant": variant_name,
                "grid_resolution_m": f"{float(grid_resolution):g}",
                "source": portable_path(source, run_dir),
                "destination": portable_path(destination, run_dir),
            }
            copied.append(item)
            group = groups.setdefault(
                grid_name,
                {
                    "grid_resolution_m": float(grid_resolution),
                    "directory": portable_path(grid_dir, run_dir),
                    "count": 0,
                    "images": [],
                },
            )
            group["count"] = int(group["count"]) + 1
            group_images = group["images"]
            if isinstance(group_images, list):
                group_images.append(item)

    copy_manifest = {
        "summary_dir": portable_path(summary_dir, run_dir),
        "count": len(copied),
        "groups": groups,
        "images": copied,
    }
    (summary_dir / "copy_manifest.json").write_text(
        json.dumps(copy_manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return copy_manifest


def _scene_record_dir(run_dir: Path, record: dict[str, object], scene_prefix: str) -> Path:
    scene_dir_value = record.get("scene_dir")
    if isinstance(scene_dir_value, str) and scene_dir_value:
        scene_dir = Path(scene_dir_value)
        return scene_dir if scene_dir.is_absolute() else run_dir / scene_dir
    return run_dir / f"{scene_prefix}_{int(record.get('scene_index', 0)):04d}"


def _resolve_visual_path(run_dir: Path, scene_dir: Path, value: object) -> str | None:
    if not isinstance(value, str) or not value:
        return None
    candidate = Path(value)
    if candidate.is_absolute():
        source = candidate
    elif (run_dir / candidate).is_file():
        source = run_dir / candidate
    else:
        source = scene_dir / candidate
    if not source.is_file():
        return None
    return portable_path(source, run_dir)


def _html_attr(value: object) -> str:
    return html.escape(str(value), quote=True)


def _html_text(value: object) -> str:
    return html.escape(str(value), quote=False)


def _html_href(path: str) -> str:
    return quote(path, safe="/._-")


def _visual_metric_items(record: dict[str, object]) -> list[tuple[str, object]]:
    metrics: list[tuple[str, object]] = []
    metrics.append(("placements", record.get("placement_count", len(record.get("placements", [])) if isinstance(record.get("placements"), list) else "")))
    quality = record.get("quality")
    if isinstance(quality, dict):
        metrics.append(("quality errors", quality.get("error_count", "")))
    label = record.get("label")
    if isinstance(label, dict):
        metrics.append(("labels", f"BS {label.get('bs_count', 0)} / UE {label.get('ue_count', 0)}"))
    procedural = record.get("procedural")
    if isinstance(procedural, dict):
        if procedural.get("layout"):
            metrics.append(("layout", procedural.get("layout", "")))
        rooms = procedural.get("rooms")
        if isinstance(rooms, list):
            metrics.append(("rooms", len(rooms)))
    return [(key, value) for key, value in metrics if value not in (None, "")]


def write_visual_index(run_dir: Path, scene_records: list[dict[str, object]], scene_prefix: str) -> str:
    """Write a lightweight HTML gallery for generated visual QA artifacts."""

    cards: list[str] = []
    for record in sorted(scene_records, key=lambda item: int(item.get("scene_index", 0))):
        scene_index = int(record.get("scene_index", 0))
        scene_key = str(record.get("scene_key") or record.get("scene_dir") or f"{scene_prefix}_{scene_index:04d}")
        scene_dir = _scene_record_dir(run_dir, record, scene_prefix)
        floorplan = record.get("floorplan")
        images: list[tuple[str, str]] = []
        if isinstance(floorplan, dict):
            geometry = floorplan.get("geometry")
            if isinstance(geometry, dict):
                raw_path = _resolve_visual_path(run_dir, scene_dir, geometry.get("raw"))
                if raw_path:
                    images.append(("floorplan", raw_path))
            class_mask = floorplan.get("class_mask")
            if isinstance(class_mask, dict):
                class_preview = _resolve_visual_path(run_dir, scene_dir, class_mask.get("preview"))
                if class_preview:
                    images.append(("class mask", class_preview))
            label_overlays = floorplan.get("label_overlays")
            if isinstance(label_overlays, list):
                for overlay in label_overlays:
                    if not isinstance(overlay, dict):
                        continue
                    overlay_path = _resolve_visual_path(run_dir, scene_dir, overlay.get("image"))
                    if overlay_path:
                        images.append((str(overlay.get("name") or "label overlay"), overlay_path))
        if not images:
            label = record.get("label")
            if isinstance(label, dict):
                variants = label.get("variants")
                if isinstance(variants, list):
                    for variant in variants:
                        if not isinstance(variant, dict):
                            continue
                        overlay = variant.get("overlay")
                        if not isinstance(overlay, dict):
                            continue
                        overlay_path = _resolve_visual_path(run_dir, scene_dir, overlay.get("image"))
                        if overlay_path:
                            images.append((str(variant.get("name") or "label overlay"), overlay_path))

        metrics_html = "".join(
            f"<span><strong>{_html_text(key)}</strong> {_html_text(value)}</span>"
            for key, value in _visual_metric_items(record)
        )
        image_html = "".join(
            (
                '<figure>'
                f'<a href="{_html_attr(_html_href(path))}"><img src="{_html_attr(_html_href(path))}" alt="{_html_attr(label)}"></a>'
                f"<figcaption>{_html_text(label)}</figcaption>"
                "</figure>"
            )
            for label, path in images
        )
        if not image_html:
            image_html = '<p class="empty">No visual artifacts were generated for this scene.</p>'
        cards.append(
            (
                '<section class="scene-card">'
                f"<h2>{_html_text(scene_key)}</h2>"
                f'<div class="metrics">{metrics_html}</div>'
                f'<div class="images">{image_html}</div>'
                "</section>"
            )
        )

    if not cards:
        cards.append('<section class="scene-card"><h2>No scenes</h2><p class="empty">No scene records were available.</p></section>')

    now = dt.datetime.now(dt.UTC).isoformat()
    html_text = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SceneGen Visual Index</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f5f6f7;
      --panel: #ffffff;
      --text: #1f2933;
      --muted: #64707d;
      --line: #d8dde3;
    }}
    body {{
      margin: 0;
      font: 14px/1.45 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      color: var(--text);
      background: var(--bg);
    }}
    header {{
      padding: 24px 28px 16px;
      border-bottom: 1px solid var(--line);
      background: var(--panel);
    }}
    h1 {{
      margin: 0 0 6px;
      font-size: 24px;
      font-weight: 650;
    }}
    .subtle {{
      color: var(--muted);
    }}
    main {{
      padding: 20px;
      display: grid;
      gap: 16px;
    }}
    .scene-card {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 16px;
      box-shadow: 0 1px 2px rgba(31, 41, 51, 0.04);
    }}
    .scene-card h2 {{
      margin: 0 0 10px;
      font-size: 17px;
      font-weight: 650;
    }}
    .metrics {{
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
      margin-bottom: 12px;
    }}
    .metrics span {{
      border: 1px solid var(--line);
      border-radius: 999px;
      padding: 3px 8px;
      color: var(--muted);
      background: #fafbfc;
    }}
    .metrics strong {{
      color: var(--text);
      font-weight: 600;
    }}
    .images {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
      gap: 12px;
      align-items: start;
    }}
    figure {{
      margin: 0;
      border: 1px solid var(--line);
      border-radius: 6px;
      overflow: hidden;
      background: #fff;
    }}
    img {{
      width: 100%;
      display: block;
      image-rendering: auto;
      background: #f0f2f4;
    }}
    figcaption {{
      padding: 7px 9px;
      color: var(--muted);
      border-top: 1px solid var(--line);
      font-size: 12px;
    }}
    .empty {{
      margin: 0;
      color: var(--muted);
    }}
  </style>
</head>
<body>
  <header>
    <h1>SceneGen Visual Index</h1>
    <div class="subtle">Run: {_html_text(run_dir.name)} · Scenes: {len(scene_records)} · Generated: {_html_text(now)}</div>
  </header>
  <main>
    {"".join(cards)}
  </main>
</body>
</html>
"""
    index_path = run_dir / "visual_index.html"
    index_path.write_text(html_text, encoding="utf-8")
    return portable_path(index_path, run_dir)
