from __future__ import annotations

import datetime as dt
import json
import math
import random
import re
import shutil
from pathlib import Path
from xml.dom import minidom
from xml.etree import ElementTree as ET

from .assets import resolve_face_sionna_material, sionna_material_itu_type
from .geometry import build_room_mesh, load_obj_material_mesh, load_obj_mesh, sample_support_point, transform_vertices
from .models import Asset, BistroBaseScene, ObjMesh, PlacedAsset, Rect2D, Room, SionnaAssetPart, SionnaXmlShape
from .paths import SIONNA_BASE_SCENE_MATERIAL, portable_path


def sanitize_path_segment(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", value).strip("._")
    return safe or "item"


def sanitize_xml_id(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("._-")
    if not safe:
        return "shape"
    if not re.match(r"[A-Za-z_]", safe):
        safe = f"shape_{safe}"
    return safe


def format_xml_float(value: float) -> str:
    if abs(value) < 1e-10:
        value = 0.0
    return f"{value:.9g}"


def relative_posix(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def write_clean_obj_subset(
    path: Path,
    object_name: str,
    vertices: list[tuple[float, float, float]],
    faces: list[list[int]],
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    index_map: dict[int, int] = {}
    subset_vertices: list[tuple[float, float, float]] = []
    for face in faces:
        for index in face:
            if index < 0 or index >= len(vertices):
                raise ValueError(f"OBJ face index out of range while writing {path}: {index}")
            if index not in index_map:
                index_map[index] = len(subset_vertices) + 1
                subset_vertices.append(vertices[index])

    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("# Generated by SceneGen for Sionna RT\n")
        handle.write(f"o {sanitize_xml_id(object_name)}\n")
        for x, y, z in subset_vertices:
            handle.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for face in faces:
            handle.write("f " + " ".join(str(index_map[index]) for index in face) + "\n")


def write_clean_obj_mesh(path: Path, object_name: str, mesh: ObjMesh) -> None:
    write_clean_obj_subset(path, object_name, mesh.vertices, mesh.faces)


def transform_matrix_for_placement(placed: PlacedAsset) -> tuple[float, ...]:
    cos_yaw = math.cos(placed.yaw)
    sin_yaw = math.sin(placed.yaw)
    return (
        cos_yaw,
        -sin_yaw,
        0.0,
        placed.x,
        sin_yaw,
        cos_yaw,
        0.0,
        placed.y,
        0.0,
        0.0,
        1.0,
        placed.z,
        0.0,
        0.0,
        0.0,
        1.0,
    )


def export_sionna_asset_parts(
    scene_dir: Path,
    assets_dir: Path,
    asset: Asset,
    cache: dict[Path, list[SionnaAssetPart]],
) -> list[SionnaAssetPart]:
    cached = cache.get(asset.obj_file)
    if cached is not None:
        return cached

    material_mesh = load_obj_material_mesh(asset.obj_file)
    faces_by_sionna: dict[str, list[list[int]]] = {}
    for source_material, faces in material_mesh.faces_by_material.items():
        material_name = resolve_face_sionna_material(asset, source_material)
        faces_by_sionna.setdefault(material_name, []).extend(faces)

    asset_dir_name = sanitize_path_segment(asset.export_name)
    asset_dir = assets_dir / asset_dir_name
    asset_stem = sanitize_path_segment(asset.export_name)
    parts: list[SionnaAssetPart] = []
    for material_name in sorted(faces_by_sionna):
        faces = faces_by_sionna[material_name]
        material_suffix = sanitize_path_segment(sionna_material_itu_type(material_name))
        path = asset_dir / f"{asset_stem}__{material_suffix}.obj"
        write_clean_obj_subset(
            path,
            f"{asset.export_name}_{material_suffix}",
            material_mesh.vertices,
            faces,
        )
        parts.append(
            SionnaAssetPart(
                filename=relative_posix(path, scene_dir),
                material_name=material_name,
                face_count=len(faces),
            )
        )

    cache[asset.obj_file] = parts
    return parts


def build_sionna_scene_xml(shapes: list[SionnaXmlShape]) -> str:
    scene = ET.Element("scene", version="3.0.0")
    for material_name in sorted({shape.material_name for shape in shapes}):
        bsdf = ET.SubElement(scene, "bsdf", type="itu-radio-material", id=material_name)
        ET.SubElement(bsdf, "string", name="type", value=sionna_material_itu_type(material_name))

    for shape_info in shapes:
        shape = ET.SubElement(scene, "shape", type="obj", id=sanitize_xml_id(shape_info.shape_id))
        ET.SubElement(shape, "string", name="filename", value=shape_info.filename)
        if shape_info.transform is not None:
            transform = ET.SubElement(shape, "transform", name="to_world")
            ET.SubElement(
                transform,
                "matrix",
                value=" ".join(format_xml_float(value) for value in shape_info.transform),
            )
        ET.SubElement(shape, "ref", id=shape_info.material_name)

    rough = ET.tostring(scene, encoding="utf-8")
    return minidom.parseString(rough).toprettyxml(indent="  ", encoding="utf-8").decode("utf-8")


def write_sionna_scene_assets(
    output_dir: Path,
    base_mesh: ObjMesh,
    placements: list[PlacedAsset],
) -> dict[str, object]:
    assets_dir = output_dir / "assets"
    empty_scene_obj = assets_dir / "empty_scene" / "scene.obj"
    write_clean_obj_mesh(empty_scene_obj, "empty_scene", base_mesh)

    shapes = [
        SionnaXmlShape(
            shape_id="empty_scene",
            filename=relative_posix(empty_scene_obj, output_dir),
            material_name=SIONNA_BASE_SCENE_MATERIAL,
        )
    ]
    asset_cache: dict[Path, list[SionnaAssetPart]] = {}
    placement_asset_parts: list[dict[str, object]] = []
    for placed in placements:
        parts = export_sionna_asset_parts(output_dir, assets_dir, placed.asset, asset_cache)
        transform = transform_matrix_for_placement(placed)
        placement_parts: list[dict[str, object]] = []
        for part in parts:
            material_suffix = sanitize_path_segment(sionna_material_itu_type(part.material_name))
            shape_id = f"{placed.instance_name}_{material_suffix}"
            shapes.append(
                SionnaXmlShape(
                    shape_id=shape_id,
                    filename=part.filename,
                    material_name=part.material_name,
                    transform=transform,
                )
            )
            placement_parts.append(
                {
                    "shape_id": sanitize_xml_id(shape_id),
                    "asset_obj": part.filename,
                    "sionna_material_name": part.material_name,
                    "itu_type": sionna_material_itu_type(part.material_name),
                    "face_count": part.face_count,
                }
            )
        placement_asset_parts.append(
            {
                "instance_name": placed.instance_name,
                "asset_name": placed.asset.name,
                "parts": placement_parts,
            }
        )

    (output_dir / "scene.xml").write_text(build_sionna_scene_xml(shapes), encoding="utf-8")
    return {
        "assets_dir": portable_path(assets_dir, output_dir),
        "empty_scene_obj": relative_posix(empty_scene_obj, output_dir),
        "scene_xml": portable_path(output_dir / "scene.xml", output_dir),
        "shape_count": len(shapes),
        "asset_file_count": sum(len(parts) for parts in asset_cache.values()) + 1,
        "materials": sorted({shape.material_name for shape in shapes}),
        "placements": placement_asset_parts,
    }


def write_obj(path: Path, room: Room, placements: list[PlacedAsset]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    room_mesh = build_room_mesh(room)
    mesh_cache: dict[Path, ObjMesh] = {}
    vertex_offset = 0
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("# Generated by SceneGen\n")
        handle.write("o generated_room\n")
        for x, y, z in room_mesh.vertices:
            handle.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for face in room_mesh.faces:
            handle.write("f " + " ".join(str(vertex_offset + index + 1) for index in face) + "\n")
        vertex_offset += len(room_mesh.vertices)

        for placed in placements:
            mesh = mesh_cache.setdefault(placed.asset.obj_file, load_obj_mesh(placed.asset.obj_file))
            handle.write(f"o {placed.instance_name}\n")
            for x, y, z in transform_vertices(mesh, placed):
                handle.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
            for face in mesh.faces:
                handle.write("f " + " ".join(str(vertex_offset + index + 1) for index in face) + "\n")
            vertex_offset += len(mesh.vertices)


def write_bistro_obj(path: Path, base_scene: BistroBaseScene, placements: list[PlacedAsset]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    base_mesh = load_obj_mesh(base_scene.scene_obj)
    mesh_cache: dict[Path, ObjMesh] = {}
    vertex_offset = 0
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("# Generated by SceneGen --mode bistro\n")
        handle.write("o empty_scene\n")
        for x, y, z in base_mesh.vertices:
            handle.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for face in base_mesh.faces:
            handle.write("f " + " ".join(str(vertex_offset + index + 1) for index in face) + "\n")
        vertex_offset += len(base_mesh.vertices)

        for placed in placements:
            mesh = mesh_cache.setdefault(placed.asset.obj_file, load_obj_mesh(placed.asset.obj_file))
            handle.write(f"o {placed.instance_name}\n")
            for x, y, z in transform_vertices(mesh, placed):
                handle.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
            for face in mesh.faces:
                handle.write("f " + " ".join(str(vertex_offset + index + 1) for index in face) + "\n")
            vertex_offset += len(mesh.vertices)


def placement_to_json(placed: PlacedAsset, path_root: Path) -> dict[str, object]:
    return {
        "instance_name": placed.instance_name,
        "asset_name": placed.asset.name,
        "asset_obj": portable_path(placed.asset.obj_file, path_root),
        "placement_class": placed.asset.placement_class,
        "sionna_materials": list(placed.asset.sionna_material_names),
        "source_to_sionna_material": placed.asset.source_to_sionna_material,
        "support_type": placed.support_type,
        "parent": placed.parent,
        "translation": [round(placed.x, 6), round(placed.y, 6), round(placed.z, 6)],
        "yaw_radians": round(placed.yaw, 6),
        "bbox": {
            "min": [round(placed.min_x, 6), round(placed.min_y, 6), round(placed.min_z, 6)],
            "max": [round(placed.max_x, 6), round(placed.max_y, 6), round(placed.max_z, 6)],
        },
        "asset_dimensions": {
            "width_x": placed.asset.width,
            "length_y": placed.asset.length,
            "height_z": placed.asset.height,
        },
    }


def write_label_json(path: Path, room: Room, rng: random.Random) -> None:
    bs_points = [
        {"x": 0.5, "y": 0.5, "z": room.height - 0.5, "label": "BS0"},
        {"x": room.width - 0.5, "y": 0.5, "z": room.height - 0.5, "label": "BS1"},
        {"x": room.width - 0.5, "y": room.length - 0.5, "z": room.height - 0.5, "label": "BS2"},
        {"x": 0.5, "y": room.length - 0.5, "z": room.height - 0.5, "label": "BS3"},
    ]
    ue_points = []
    for index in range(12):
        ue_points.append(
            {
                "x": round(rng.uniform(1.0, room.width - 1.0), 3),
                "y": round(rng.uniform(1.0, room.length - 1.0), 3),
                "z": 1.5,
                "label": f"UE{index}",
            }
        )
    payload = {
        "scene_file": portable_path(path.parent / "scene.obj", path.parent),
        "groups": [{"name": "generated_default", "note": "", "bs_points": bs_points, "ue_points": ue_points}],
    }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def write_bistro_label_json(path: Path, base_scene: BistroBaseScene, rng: random.Random) -> None:
    if base_scene.label_json is not None:
        payload = json.loads(base_scene.label_json.read_text(encoding="utf-8"))
        payload["scene_file"] = portable_path(path.parent / "scene.obj", path.parent)
    else:
        min_x, min_y, _ = base_scene.bbox_min
        max_x, max_y, max_z = base_scene.bbox_max
        bs_points = [
            {"x": round(min_x + 1.0, 3), "y": round(min_y + 1.0, 3), "z": round(max_z - 0.8, 3), "label": "BS0"},
            {"x": round(max_x - 1.0, 3), "y": round(min_y + 1.0, 3), "z": round(max_z - 0.8, 3), "label": "BS1"},
            {"x": round(max_x - 1.0, 3), "y": round(max_y - 1.0, 3), "z": round(max_z - 0.8, 3), "label": "BS2"},
            {"x": round(min_x + 1.0, 3), "y": round(max_y - 1.0, 3), "z": round(max_z - 0.8, 3), "label": "BS3"},
        ]
        ue_points = []
        for index in range(12):
            x, y = sample_support_point(rng, base_scene.floor_triangles)
            ue_points.append(
                {"x": round(x, 3), "y": round(y, 3), "z": round(base_scene.floor_z + 1.5, 3), "label": f"UE{index}"}
            )
        payload = {
            "scene_file": portable_path(path.parent / "scene.obj", path.parent),
            "groups": [{"name": "bistro_generated_default", "note": "", "bs_points": bs_points, "ue_points": ue_points}],
        }
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def write_scene_files(
    output_dir: Path,
    room: Room,
    placements: list[PlacedAsset],
    scene_index: int,
    seed: int,
    rng: random.Random,
) -> dict[str, object]:
    output_dir.mkdir(parents=True, exist_ok=True)
    write_obj(output_dir / "scene.obj", room, placements)
    sionna_assets = write_sionna_scene_assets(output_dir, build_room_mesh(room), placements)
    write_label_json(output_dir / "label.json", room, rng)
    placement_payload = {
        "scene_index": scene_index,
        "seed": seed,
        "mode": "generated",
        "room": {"width": room.width, "length": room.length, "height": room.height},
        "forbidden_xy_rects": [],
        "forbidden_z_ignored": False,
        "sionna_assets": sionna_assets,
        "placement_count": len(placements),
        "placements": [placement_to_json(placement, output_dir) for placement in placements],
    }
    (output_dir / "placements.json").write_text(json.dumps(placement_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return scene_record(output_dir, scene_index, seed, sionna_assets, placements)


def write_bistro_scene_files(
    output_dir: Path,
    base_scene: BistroBaseScene,
    placements: list[PlacedAsset],
    scene_index: int,
    seed: int,
    rng: random.Random,
    forbidden_xy_rects: tuple[Rect2D, ...],
) -> dict[str, object]:
    output_dir.mkdir(parents=True, exist_ok=True)
    write_bistro_obj(output_dir / "scene.obj", base_scene, placements)
    sionna_assets = write_sionna_scene_assets(output_dir, load_obj_mesh(base_scene.scene_obj), placements)
    write_bistro_label_json(output_dir / "label.json", base_scene, rng)
    placement_payload = {
        "scene_index": scene_index,
        "seed": seed,
        "mode": "bistro",
        "forbidden_xy_rects": [list(rect) for rect in forbidden_xy_rects],
        "forbidden_z_ignored": True,
        "sionna_assets": sionna_assets,
        "base_scene": base_scene_summary(base_scene, output_dir),
        "placement_count": len(placements),
        "placements": [placement_to_json(placement, output_dir) for placement in placements],
    }
    (output_dir / "placements.json").write_text(json.dumps(placement_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return scene_record(output_dir, scene_index, seed, sionna_assets, placements)


def scene_record(
    output_dir: Path,
    scene_index: int,
    seed: int,
    sionna_assets: dict[str, object],
    placements: list[PlacedAsset],
) -> dict[str, object]:
    run_dir = output_dir.parent
    return {
        "scene_index": scene_index,
        "seed": seed,
        "scene_dir": portable_path(output_dir, run_dir),
        "scene_obj": portable_path(output_dir / "scene.obj", run_dir),
        "scene_xml": portable_path(output_dir / "scene.xml", run_dir),
        "assets_dir": portable_path(output_dir / "assets", run_dir),
        "sionna_shape_count": sionna_assets["shape_count"],
        "sionna_materials": sionna_assets["materials"],
        "placement_count": len(placements),
    }


def base_scene_summary(base_scene: BistroBaseScene, path_root: Path | None = None) -> dict[str, object]:
    root = path_root or base_scene.base_dir
    return {
        "base_dir": portable_path(base_scene.base_dir, root),
        "scene_obj": portable_path(base_scene.scene_obj, root),
        "bbox_min": [round(value, 6) for value in base_scene.bbox_min],
        "bbox_max": [round(value, 6) for value in base_scene.bbox_max],
        "floor_z": round(base_scene.floor_z, 6),
        "floor_triangle_count": len(base_scene.floor_triangles),
        "floor_area": round(sum(tri.area for tri in base_scene.floor_triangles), 6),
        "support_surface_count": len(base_scene.support_surfaces),
        "static_obstacle_count": len(base_scene.static_obstacles),
    }


def make_timestamp() -> str:
    return dt.datetime.now().strftime("%Y%m%d%H%M%S")


def collect_scene_objs(run_dir: Path, scene_records: list[dict[str, object]], scene_prefix: str) -> dict[str, object]:
    summary_dir = run_dir / "summary_obj"
    summary_dir.mkdir(parents=True, exist_ok=True)
    copied: list[dict[str, str]] = []
    for record in scene_records:
        scene_index = int(record["scene_index"])
        source = Path(str(record["scene_obj"]))
        if not source.is_absolute():
            source = run_dir / source
        destination = summary_dir / f"{scene_prefix}_{scene_index:04d}.obj"
        shutil.copy2(source, destination)
        copied.append(
            {
                "source": portable_path(source, run_dir),
                "destination": portable_path(destination, run_dir),
            }
        )

    copy_manifest = {
        "summary_dir": portable_path(summary_dir, run_dir),
        "count": len(copied),
        "objects": copied,
    }
    (summary_dir / "copy_manifest.json").write_text(
        json.dumps(copy_manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return copy_manifest


def collect_raw_floorplans(run_dir: Path, scene_records: list[dict[str, object]], scene_prefix: str) -> dict[str, object]:
    summary_dir = run_dir / "summary_floorplan_raw"
    summary_dir.mkdir(parents=True, exist_ok=True)
    copied: list[dict[str, str]] = []

    for record in scene_records:
        scene_index = int(record["scene_index"])
        floorplan = record.get("floorplan")
        if not isinstance(floorplan, dict) or not floorplan.get("ok", False):
            continue
        geometry = floorplan.get("geometry")
        if not isinstance(geometry, dict):
            continue
        raw_path = geometry.get("raw")
        if not isinstance(raw_path, str) or not raw_path:
            continue

        scene_dir = Path(str(record["scene_dir"]))
        if not scene_dir.is_absolute():
            scene_dir = run_dir / scene_dir
        source = Path(raw_path)
        if not source.is_absolute():
            source = scene_dir / source
        if not source.is_file():
            continue

        destination = summary_dir / f"{scene_prefix}_{scene_index:04d}_geometry_raw.png"
        shutil.copy2(source, destination)
        copied.append(
            {
                "scene_index": str(scene_index),
                "source": portable_path(source, run_dir),
                "destination": portable_path(destination, run_dir),
            }
        )

    copy_manifest = {
        "summary_dir": portable_path(summary_dir, run_dir),
        "count": len(copied),
        "images": copied,
    }
    (summary_dir / "copy_manifest.json").write_text(
        json.dumps(copy_manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return copy_manifest
